
const images = {
    image2: require('./assets/my_artwork_2.png'),
    image3: require('./assets/my_artwork_3.png'),
    image4: require('./assets/my_artwork_4.png'),
    image5: require('./assets/my_artwork_5.png'),
    image6: require('./assets/my_artwork_6.png'),
}

export const auctionArtworks = [
    {   
        id: 'a2',
        artwork: "Silent Color",
        artImage : images.image2,
        artist: 'Pawel Czerwinski',
        artistTitle: 'Creator',
        liked: 'false',
        artImageURL: images.image2,
        artistImageURL: '../../../assets/artist_1.png',
        sold: true, 
        soldFor: '2.00'
    },
    {   
        id: 'a3',
        artwork: "George",
        artImage : images.image3,
        artist: 'Pawel Czerwinski',
        artistTitle: 'Creator',
        liked: 'false',
        artImageURL: images.image3,
        artistImageURL: '../../../assets/artist_3.png',
        sold: true,
        soldFor: '2.00',
    },
    {   
        id: 'a4',
        artwork: "Mirror",
        artImage : images.image4,
        artist: 'Pawel Czerwinski',
        artistTitle: 'Creator',
        liked: 'false',
        artImageURL: images.image4,
        artistImageURL: '../../../assets/artist_1.png',
        sold: false,
        currentBid: '2.00',
        remainingTimeMinutes: 27,
        remainingTimeSeconds: 30,
    },
    {   
        id: 'a5',
        artwork: "Artwork",
        artImage : images.image5,
        artist: 'Pawel Czerwinski',
        artistTitle: 'Creator',
        liked: 'false',
        artImageURL: images.image5,
        artistImageURL: '../../../assets/artist_1.png',
        sold: false,
        currentBid: '2.00',
        remainingTimeMinutes: 27,
        remainingTimeSeconds: 30,
    },
    {   
        id: 'a6',
        artwork: "Shedd Aquarium",
        artImage : images.image6,
        artist: 'Pawel Czerwinski',
        artistTitle: 'Creator',
        liked: 'false',
        artImageURL: images.image6,
        artistImageURL: '../../../assets/artist_1.png',
        sold: false,
        currentBid: '2.00',
        remainingTimeMinutes: 27,
        remainingTimeSeconds: 30,
    }
]